/**
 * Farmer column map - the single source of truth for the farmer export, the
 * downloadable template and the Excel importer.
 *
 * Headers keep the spellings the previous importer accepted ("First Name",
 * "Land Holding", "Crop1.No_Of_Plants", ...), including the "Middl Name" typo
 * it tolerated, which is carried here as an alias.
 */

import { ExcelSheetDefinition } from '../../excel/excelColumn';
import { formatDateCell, formatName } from '../../excel/excelValue';
import { Crop } from '../entity/crop.entity';
import { Farmer, LandHoldingStatus, LandStatus } from '../entity/farmer.entity';
import { Status } from '../../utils/status.enum';

/**
 * Gender is a free varchar in the database rather than an enum, so these are
 * offered as a dropdown for convenience but anything else already on record
 * still exports and imports unchanged.
 */
const GENDER_CHOICES = ['Male', 'Female', 'Other'] as const;

const CROP_GROUP = {
  prefix: 'Crop',
  keyHeader: 'Crop',
  maxOnExport: 5,
  note: 'Each block is one crop grown by the farmer.',
  columns: [
    {
      header: 'Crop',
      maps: 'crop.crops -> product.product_name',
      width: 24,
      note: 'Must match an existing product name. The row is skipped if it does not.',
      get: (crop: Crop) => crop.crop?.name,
    },
    {
      header: 'Variety',
      maps: 'crop.variety',
      width: 20,
      get: (crop: Crop) => crop.variety,
    },
    {
      header: 'No_Of_Plants',
      maps: 'crop.noOfPlants',
      type: 'integer' as const,
      aliases: ['No Of Plants', 'Number Of Plants'],
      width: 16,
      get: (crop: Crop) => crop.noOfPlants,
    },
    {
      header: 'Pruning Date',
      maps: 'crop.pruningDate',
      type: 'date' as const,
      width: 18,
      get: (crop: Crop) => formatDateCell(crop.pruningDate),
    },
    {
      header: 'Expected Harvest Date',
      maps: 'crop.expectedHarvestDate',
      type: 'date' as const,
      width: 22,
      get: (crop: Crop) => formatDateCell(crop.expectedHarvestDate),
    },
    {
      header: 'Expected Quantity (Tonnes)',
      maps: 'crop.expectedQuantityInTonnes',
      type: 'number' as const,
      width: 24,
      get: (crop: Crop) => crop.expectedQuantityInTonnes,
    },
  ],
};

export const FARMER_SHEET: ExcelSheetDefinition<Farmer> = {
  sheetName: 'Farmers',

  columns: [
    {
      header: 'Farmer Code',
      maps: 'farmer.farmerCode',
      readOnly: true,
      width: 18,
      note: 'Generated by the system. Leave blank when importing.',
      get: (farmer) => farmer.farmerCode,
    },
    {
      header: 'First Name',
      maps: 'farmer.farmerfName',
      required: true,
      width: 20,
      get: (farmer) => farmer.farmerfName,
    },
    {
      header: 'Middle Name',
      maps: 'farmer.farmermName',
      aliases: ['Middl Name'],
      width: 20,
      get: (farmer) => farmer.farmermName,
    },
    {
      header: 'Last Name',
      maps: 'farmer.farmerlName',
      width: 20,
      get: (farmer) => farmer.farmerlName,
    },
    {
      header: 'Primary Mobile No',
      maps: 'farmer.primaryMobileNo',
      required: true,
      width: 20,
      get: (farmer) => farmer.primaryMobileNo,
    },
    {
      header: 'Secondary Mobile No',
      maps: 'farmer.secondaryMobileNo',
      width: 20,
      get: (farmer) => farmer.secondaryMobileNo,
    },
    {
      header: 'Email',
      maps: 'farmer.email',
      width: 28,
      get: (farmer) => farmer.email,
    },
    {
      header: 'Gender',
      maps: 'farmer.gender',
      enumValues: GENDER_CHOICES,
      width: 14,
      get: (farmer) => farmer.gender,
    },
    {
      header: 'Date Of Birth',
      maps: 'farmer.dob',
      type: 'date',
      width: 18,
      get: (farmer) => formatDateCell(farmer.dob),
    },
    {
      header: 'Land Holding',
      maps: 'farmer.landHoldingStatus',
      enumValues: Object.values(LandHoldingStatus),
      width: 18,
      get: (farmer) => farmer.landHoldingStatus,
    },
    {
      header: 'Land Status',
      maps: 'farmer.landStatus',
      enumValues: Object.values(LandStatus),
      width: 18,
      get: (farmer) => farmer.landStatus,
    },
    {
      header: 'Total Land Area',
      maps: 'farmer.totalLandArea',
      type: 'number',
      width: 18,
      note: 'In acres.',
      get: (farmer) => farmer.totalLandArea,
    },
    {
      header: 'Cultivation Area',
      maps: 'farmer.cultivationArea',
      type: 'number',
      width: 18,
      note: 'In acres.',
      get: (farmer) => farmer.cultivationArea,
    },
    {
      header: 'Farmer Grading',
      maps: 'farmer.farmerGrading',
      width: 18,
      get: (farmer) => farmer.farmerGrading,
    },
    {
      header: 'How Do You Sell',
      maps: 'farmer.howDoYouSell',
      width: 26,
      get: (farmer) => farmer.howDoYouSell,
    },
    {
      header: 'Date Of Visit',
      maps: 'farmer.dateOfVisit',
      type: 'date',
      width: 18,
      get: (farmer) => formatDateCell(farmer.dateOfVisit),
    },
    {
      header: '7/12 Number',
      maps: 'farmer.sevenTwelveNo',
      aliases: ['Seven Twelve No', '7/12 No'],
      width: 20,
      get: (farmer) => farmer.sevenTwelveNo,
    },
    {
      header: '7/12 Copy',
      maps: 'farmer.sevenTwelveCopy',
      aliases: ['Seven Twelve Copy'],
      width: 36,
      readOnly: true,
      note: 'Document URL. Uploaded through the app, so it is shown here but not imported.',
      get: (farmer) => farmer.sevenTwelveCopy,
    },
    {
      header: 'ID Proof Number',
      maps: 'farmer.idProofNo',
      aliases: ['Id Proof No'],
      width: 20,
      get: (farmer) => farmer.idProofNo,
    },
    {
      header: 'ID Proof Copy',
      maps: 'farmer.idProofCopy',
      width: 36,
      readOnly: true,
      note: 'Document URL. Uploaded through the app, so it is shown here but not imported.',
      get: (farmer) => farmer.idProofCopy,
    },
    {
      header: 'Farmer Photo',
      maps: 'farmer.farmerPhoto',
      width: 36,
      readOnly: true,
      note: 'Image URL. Uploaded through the app, so it is shown here but not imported.',
      get: (farmer) => farmer.farmerPhoto,
    },
    {
      header: 'Farm Photo',
      maps: 'farmer.farmPhoto',
      width: 36,
      readOnly: true,
      note: 'Image URL. Uploaded through the app, so it is shown here but not imported.',
      get: (farmer) => farmer.farmPhoto,
    },

    // ── Residential address ────────────────────────────────────────────────
    {
      header: 'Residential Address1',
      maps: 'addresses.address1',
      width: 30,
      get: (farmer) => farmer.residensialAddress?.address1,
    },
    {
      header: 'Residential Address2',
      maps: 'addresses.address2',
      width: 30,
      get: (farmer) => farmer.residensialAddress?.address2,
    },
    {
      header: 'Residential Location',
      maps: 'addresses.location',
      width: 22,
      get: (farmer) => farmer.residensialAddress?.location,
    },
    {
      header: 'Residential City',
      maps: 'addresses.city',
      width: 20,
      get: (farmer) => farmer.residensialAddress?.city,
    },
    {
      header: 'Residential State',
      maps: 'addresses.state',
      width: 20,
      get: (farmer) => farmer.residensialAddress?.state,
    },
    {
      header: 'Residential Pincode',
      maps: 'addresses.pincode',
      width: 16,
      get: (farmer) => farmer.residensialAddress?.pincode,
    },

    // ── Farm address ───────────────────────────────────────────────────────
    {
      header: 'Farm Address1',
      maps: 'addresses.address1',
      width: 30,
      get: (farmer) => farmer.farmAddress?.address1,
    },
    {
      header: 'Farm Address2',
      maps: 'addresses.address2',
      width: 30,
      get: (farmer) => farmer.farmAddress?.address2,
    },
    {
      header: 'Farm Location',
      maps: 'addresses.location',
      width: 22,
      get: (farmer) => farmer.farmAddress?.location,
    },
    {
      header: 'Farm City',
      maps: 'addresses.city',
      width: 20,
      get: (farmer) => farmer.farmAddress?.city,
    },
    {
      header: 'Farm State',
      maps: 'addresses.state',
      width: 20,
      get: (farmer) => farmer.farmAddress?.state,
    },
    {
      header: 'Farm Pincode',
      maps: 'addresses.pincode',
      width: 16,
      get: (farmer) => farmer.farmAddress?.pincode,
    },

    {
      header: 'Status',
      maps: 'farmer.status',
      type: 'enum',
      enumValues: Object.values(Status),
      width: 16,
      readOnly: true,
      note: 'Set by the approval flow. New imports always start as "pending".',
      get: (farmer) => farmer.status,
    },
    {
      header: 'Created By',
      maps: 'farmer.created_by -> users.firstName + lastName',
      width: 24,
      readOnly: true,
      note: 'The employee who created the record. On import this is the logged-in user.',
      get: (farmer) =>
        formatName(farmer.createdBy?.firstName, farmer.createdBy?.lastName),
    },
  ],

  groups: [{ ...CROP_GROUP, children: (farmer: Farmer) => farmer.crops ?? [] }],
};

export const FARMER_CROP_GROUP = CROP_GROUP;
