/**
 * Product column map - the single source of truth for the product export, the
 * downloadable template and the Excel importer.
 *
 * Headers match the ones the previous importer already accepted ("Product
 * Name", "Shelf Life (Days)", "Variant1.Count", ...) so spreadsheets staff
 * already have keep working; the columns added here are the product fields the
 * old importer silently ignored.
 */

import { ExcelSheetDefinition } from '../../../excel/excelColumn';
import { Product } from '../entity/product.entity';
import { ProductVarient } from '../../productVarient/entity/productVarient.entity';
import { Acceptability, QualityParameter } from '../entity/quantityParameter.entity';

const VARIANT_GROUP = {
  prefix: 'Variant',
  keyHeader: 'Count',
  maxOnExport: 5,
  note: 'Each block is one packing variant of the product.',
  columns: [
    {
      header: 'Variant Name',
      maps: 'productVarient.variantName',
      readOnly: true,
      width: 24,
      note: 'Built from the product name and the variant parts below.',
      get: (variant: ProductVarient) => variant.variantName,
    },
    {
      header: 'Variant Code',
      maps: 'productVarient.varient_code',
      readOnly: true,
      width: 18,
      get: (variant: ProductVarient) => variant.variantCode,
    },
    {
      header: 'Count',
      maps: 'productVarient.count',
      width: 14,
      get: (variant: ProductVarient) => variant.count,
    },
    {
      header: 'Size',
      maps: 'productVarient.size',
      width: 14,
      get: (variant: ProductVarient) => variant.size,
    },
    {
      header: 'Variety',
      maps: 'productVarient.variety',
      width: 18,
      get: (variant: ProductVarient) => variant.variety,
    },
    {
      header: 'Origin',
      maps: 'productVarient.origin',
      width: 18,
      get: (variant: ProductVarient) => variant.origin,
    },
    {
      header: 'Brand',
      maps: 'productVarient.brand',
      width: 18,
      get: (variant: ProductVarient) => variant.brand,
    },
  ],
};

const PARAMETER_GROUP = {
  prefix: 'Parameter',
  keyHeader: 'Name',
  maxOnExport: 5,
  note: 'Quality parameters checked when this product is received.',
  columns: [
    {
      header: 'Name',
      maps: 'quality_parameters.parameter_name',
      width: 26,
      get: (parameter: QualityParameter) => parameter.name,
    },
    {
      header: 'Type',
      maps: 'quality_parameters.type',
      type: 'enum' as const,
      enumValues: Object.values(Acceptability),
      width: 16,
      note: 'Defaults to "good" when left blank.',
      get: (parameter: QualityParameter) => parameter.type,
    },
  ],
};

export const PRODUCT_SHEET: ExcelSheetDefinition<Product> = {
  sheetName: 'Products',

  columns: [
    {
      header: 'Product Code',
      maps: 'product.product_code',
      readOnly: true,
      width: 18,
      note: 'Generated by the system from the prefix. Leave blank when importing.',
      get: (product) => product.productCode,
    },
    {
      header: 'Product Name',
      maps: 'product.product_name',
      required: true,
      width: 30,
      get: (product) => product.name,
    },
    {
      header: 'Product Code Prefix',
      maps: 'product.prefix',
      required: true,
      width: 20,
      note:
        'Used to build the product code, e.g. "ONI" gives ONI0001, ONI0002, ... ' +
        'Stored upper-cased, so "oni" and "ONI" share one series.',
      get: (product) => product.prefix,
    },
    {
      header: 'Description',
      maps: 'product.description',
      width: 40,
      get: (product) => product.description,
    },
    {
      header: 'Product Image',
      maps: 'product.product_image',
      readOnly: true,
      width: 40,
      note: 'Image URL. Uploaded through the app, so it is shown here but not imported.',
      get: (product) => product.image,
    },
    {
      header: 'Classification',
      maps: 'product_classification.name',
      width: 24,
      note:
        'Matched ignoring case, spaces and punctuation - "Fresh Produce" finds an ' +
        'existing "fresh produce". Created only if there is no match.',
      get: (product) => product.classification?.name,
    },
    {
      header: 'Category',
      maps: 'product_category.name',
      width: 24,
      note:
        'Matched ignoring case, spaces and punctuation. Created only if there is ' +
        'no match.',
      get: (product) => product.category?.name,
    },
    {
      header: 'Subcategory',
      maps: 'product_subcategory.name',
      width: 24,
      note:
        'Looked up within the given Category, ignoring case, spaces and ' +
        'punctuation. Created under that Category only if there is no match.',
      get: (product) => product.subcategory?.name,
    },
    {
      header: 'UOM',
      maps: 'uom.unit',
      width: 16,
      note:
        'Unit of measure, e.g. "Kilogram". Matched ignoring case, spaces and ' +
        'punctuation. Created only if there is no match.',
      get: (product) => product.uom?.unit,
    },
    {
      header: 'UOM Abbreviation',
      maps: 'uom.abbreviation',
      width: 18,
      note: 'Only used when a new UOM has to be created.',
      get: (product) => product.uom?.abbreviation,
    },
    {
      header: 'UOM Description',
      maps: 'uom.description',
      width: 28,
      note: 'Only used when a new UOM has to be created.',
      get: (product) => product.uom?.description,
    },
    {
      header: 'Packing Type',
      maps: 'product.packing_type',
      width: 22,
      get: (product) => product.packingType,
    },
    {
      header: 'Shelf Life (Days)',
      maps: 'product.shelf_life',
      type: 'integer',
      width: 18,
      get: (product) => product.shelfLife,
    },
    {
      header: 'Storage Temp (°C)',
      maps: 'product.storage_temp',
      type: 'integer',
      aliases: ['Storage Temp (C)', 'Storage Temp'],
      width: 18,
      note: 'Whole degrees Celsius.',
      get: (product) => product.storageTemp,
    },
    {
      header: 'Threshold Stock',
      maps: 'product.thresholdStock',
      type: 'integer',
      width: 18,
      note: 'Stock level at which a low-stock alert is raised.',
      get: (product) => product.thresholdStock,
    },
  ],

  groups: [
    { ...VARIANT_GROUP, children: (product: Product) => product.variant ?? [] },
    {
      ...PARAMETER_GROUP,
      children: (product: Product) => product.qualityParameters ?? [],
    },
  ],
};

export const PRODUCT_VARIANT_GROUP = VARIANT_GROUP;
export const PRODUCT_PARAMETER_GROUP = PARAMETER_GROUP;
